version: '4.42'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=User
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    restart: always

volumes:
  mongodb_data:
